

// Generated helper templates
// Generated items
// AsterNET.ARI\ARICodeGen\Templates\ARIClient.cs
// AsterNET.ARI\ARICodeGen\Templates\RecordingsActions.cs
// AsterNET.ARI\ARICodeGen\Templates\LiveRecording.cs
// AsterNET.ARI\ARICodeGen\Templates\StoredRecording.cs
// AsterNET.ARI\ARICodeGen\Templates\SoundsActions.cs
// AsterNET.ARI\ARICodeGen\Templates\Sound.cs
// AsterNET.ARI\ARICodeGen\Templates\FormatLangPair.cs
// AsterNET.ARI\ARICodeGen\Templates\PlaybacksActions.cs
// AsterNET.ARI\ARICodeGen\Templates\Playback.cs
// AsterNET.ARI\ARICodeGen\Templates\DeviceStatesActions.cs
// AsterNET.ARI\ARICodeGen\Templates\DeviceState.cs
// AsterNET.ARI\ARICodeGen\Templates\EndpointsActions.cs
// AsterNET.ARI\ARICodeGen\Templates\Endpoint.cs
// AsterNET.ARI\ARICodeGen\Templates\ApplicationsActions.cs
// AsterNET.ARI\ARICodeGen\Templates\Application.cs
// AsterNET.ARI\ARICodeGen\Templates\AsteriskActions.cs
// AsterNET.ARI\ARICodeGen\Templates\SetId.cs
// AsterNET.ARI\ARICodeGen\Templates\StatusInfo.cs
// AsterNET.ARI\ARICodeGen\Templates\SystemInfo.cs
// AsterNET.ARI\ARICodeGen\Templates\AsteriskInfo.cs
// AsterNET.ARI\ARICodeGen\Templates\BuildInfo.cs
// AsterNET.ARI\ARICodeGen\Templates\ConfigInfo.cs
// AsterNET.ARI\ARICodeGen\Templates\Variable.cs
// AsterNET.ARI\ARICodeGen\Templates\ChannelsActions.cs
// AsterNET.ARI\ARICodeGen\Templates\CallerID.cs
// AsterNET.ARI\ARICodeGen\Templates\Channel.cs
// AsterNET.ARI\ARICodeGen\Templates\Dialed.cs
// AsterNET.ARI\ARICodeGen\Templates\DialplanCEP.cs
// AsterNET.ARI\ARICodeGen\Templates\BridgesActions.cs
// AsterNET.ARI\ARICodeGen\Templates\Bridge.cs
// AsterNET.ARI\ARICodeGen\Templates\EventsActions.cs
// AsterNET.ARI\ARICodeGen\Templates\StasisStartEvent.cs
// AsterNET.ARI\ARICodeGen\Templates\StasisEndEvent.cs
// AsterNET.ARI\ARICodeGen\Templates\DialEvent.cs
// AsterNET.ARI\ARICodeGen\Templates\EndpointStateChangeEvent.cs
// AsterNET.ARI\ARICodeGen\Templates\ChannelVarsetEvent.cs
// AsterNET.ARI\ARICodeGen\Templates\ChannelHangupRequestEvent.cs
// AsterNET.ARI\ARICodeGen\Templates\ChannelDialplanEvent.cs
// AsterNET.ARI\ARICodeGen\Templates\ChannelUsereventEvent.cs
// AsterNET.ARI\ARICodeGen\Templates\BridgeBlindTransferEvent.cs
// AsterNET.ARI\ARICodeGen\Templates\BridgeDestroyedEvent.cs
// AsterNET.ARI\ARICodeGen\Templates\ChannelEnteredBridgeEvent.cs
// AsterNET.ARI\ARICodeGen\Templates\BridgeAttendedTransferEvent.cs
// AsterNET.ARI\ARICodeGen\Templates\RecordingFinishedEvent.cs
// AsterNET.ARI\ARICodeGen\Templates\BridgeMergedEvent.cs
// AsterNET.ARI\ARICodeGen\Templates\RecordingFailedEvent.cs
// AsterNET.ARI\ARICodeGen\Templates\PlaybackStartedEvent.cs
// AsterNET.ARI\ARICodeGen\Templates\Event.cs
// AsterNET.ARI\ARICodeGen\Templates\DeviceStateChangedEvent.cs
// AsterNET.ARI\ARICodeGen\Templates\ChannelDestroyedEvent.cs
// AsterNET.ARI\ARICodeGen\Templates\ChannelLeftBridgeEvent.cs
// AsterNET.ARI\ARICodeGen\Templates\RecordingStartedEvent.cs
// AsterNET.ARI\ARICodeGen\Templates\PlaybackFinishedEvent.cs
// AsterNET.ARI\ARICodeGen\Templates\ChannelStateChangeEvent.cs
// AsterNET.ARI\ARICodeGen\Templates\ApplicationReplacedEvent.cs
// AsterNET.ARI\ARICodeGen\Templates\Message.cs
// AsterNET.ARI\ARICodeGen\Templates\ChannelCreatedEvent.cs
// AsterNET.ARI\ARICodeGen\Templates\MissingParams.cs
// AsterNET.ARI\ARICodeGen\Templates\BridgeCreatedEvent.cs
// AsterNET.ARI\ARICodeGen\Templates\ChannelDtmfReceivedEvent.cs
// AsterNET.ARI\ARICodeGen\Templates\ChannelCallerIdEvent.cs
